// ============================================================
// DATOS DE LA PORRA DEL MUNDIAL
// Edita solo este archivo cuando haya nuevos resultados.
// No toques index.html.
// ============================================================

// 1) Lista de participantes (nombres tal cual quieres que aparezcan)
const participantes = [
  "José Manuel Cabeza Moreno (Cali)",
  "Miguel Ángel López Martín",
  "Roberto Quintero Sánchez",
  "Sergio Conde Molina",
  "Jaime Borrallo Quiveu",
  "Carlos Molina Prieto",
  "Ángel Manuel Borrega Infante",
  "Stancu Zoran Stefan christian",
  "Rocio Martin Rojas",
  "Antonio Vasluianu",
  "Daniel Garrocho Bogado",
  "Sara Fernández",
  "Rodrigo Exojo Pérez",
  "Silvia Martín Rojas",
  "Ismael Molina Pérez",
  "Oscar De Haro Alcocer",
  "Domingo Rodríguez Gómez",
  "Tomas Doblado Beltrán",
  "Juan Pablo Cerezo Pérez",
  "Jose Angel Maestre Naranjo",
  "Juan Pablo Cerezo Bogado",
  "Rafael Bonilla García",
  "Alvaro Quintero Domiguez",
  "Alejandro Garcia Ponce",
  "Alejandro Quintero Vázquez",
  "Ivan Oliva Rojas",
  "Germán Rojas",
  "Arturo Díaz Prieto",
  "José Manuel Rodríguez Infante",
  "Pedro López",
  "Jesús Ortega",
  "Antonio Blanco Mendez",
  "Francisco José Robles Garrocho",
  "Titola",
  "Manuel Ramon Del Cacho Azcarate",
  "Abraham Márquez Romero",
  "Javier Gavaldá Pérez",
  "Alejandra Domínguez Pozo",
  "Miguel Angel Lopez del valle",
  "Rares Florea",
  "Francis Gil",
  "Joaquín Rodríguez Rodríguez",
  "Juan Luis Garcia Lopez",
  "José Manuel Molina García",
  "Marco Rodríguez Moreno",
  "Antonio Jesús López del Valle",
  "Pedro Exojo Asensio",
  "Pedro Julián Exojo Pérez",
  "Juanma Vázquez (morris)",
  "Carlos Silverio",
  "Gonzalo Gil García",
  "Jose Antonio Aguilera Gómez",
  "Borja Sierra Velázquez",
  "Juan Carlos Molina Camacho",
  "Jorge Luis Rojas Domínguez",
  "Eusebio García Garrocho",
  "Ismael Gómez Cumbreras",
  "Rafa Márquez",
  "Fran Muñoz Muñoz",
  "Jawe Gómez Franco",
  "Arturo Diaz Rosado",
  "Jonathan Domínguez Donoso",
  "Ángel Ponce de Leon Madueño",
  "José Vázquez Garrocho",
  "RoRo Riquelme",
  "Andrea Rodríguez",
  "Alejandra Borrega Martin",
  "Miguel García Garrocho",
  "Manuel Alejandro",
  "Manuel Pérez",
  "Isaías Vázquez Cabeza"
];

// 2) Fases/partidos jugados, con los puntos que se llevó cada participante en ESA fase.
//    - "resultado" es solo informativo (se muestra en la web).
//    - En "puntos" pon el número de puntos que ganó cada participante en esa fase (0 si no acertó nada).
//    - Añade un nuevo objeto { ... } al final del array cada vez que termine una fase/partido nuevo.
//
//    Puntuación por fase: fase de grupos = 1 pto/partido acertado, dieciseisavos = 1 pto/partido acertado,
//    octavos = 2 ptos/partido acertado. Los tres bloques de abajo ya están calculados a partir de los
//    PDFs de resultados que nos pasó tu primo, y la suma coincide exactamente con la clasificación
//    acumulada que nos dio antes.
const partidos = [
  {
    fecha: "2026-06-25",
    equipos: "Fase de grupos (1 punto por partido acertado)",
    resultado: "48 partidos de grupos",
    puntos: {
      "José Manuel Cabeza Moreno (Cali)": 8,
      "Miguel Ángel López Martín": 6,
      "Roberto Quintero Sánchez": 6,
      "Sergio Conde Molina": 7,
      "Jaime Borrallo Quiveu": 6,
      "Carlos Molina Prieto": 7,
      "Ángel Manuel Borrega Infante": 7,
      "Stancu Zoran Stefan christian": 7,
      "Rocio Martin Rojas": 7,
      "Antonio Vasluianu": 5,
      "Daniel Garrocho Bogado": 8,
      "Sara Fernández": 10,
      "Rodrigo Exojo Pérez": 8,
      "Silvia Martín Rojas": 11,
      "Ismael Molina Pérez": 6,
      "Oscar De Haro Alcocer": 9,
      "Domingo Rodríguez Gómez": 5,
      "Tomas Doblado Beltrán": 9,
      "Juan Pablo Cerezo Pérez": 9,
      "Jose Angel Maestre Naranjo": 7,
      "Juan Pablo Cerezo Bogado": 5,
      "Rafael Bonilla García": 2,
      "Alvaro Quintero Domiguez": 9,
      "Alejandro Garcia Ponce": 6,
      "Alejandro Quintero Vázquez": 4,
      "Ivan Oliva Rojas": 4,
      "Germán Rojas": 8,
      "Arturo Díaz Prieto": 4,
      "José Manuel Rodríguez Infante": 13,
      "Pedro López": 13,
      "Jesús Ortega": 6,
      "Antonio Blanco Mendez": 12,
      "Francisco José Robles Garrocho": 6,
      "Titola": 7,
      "Manuel Ramon Del Cacho Azcarate": 8,
      "Abraham Márquez Romero": 9,
      "Javier Gavaldá Pérez": 10,
      "Alejandra Domínguez Pozo": 6,
      "Miguel Angel Lopez del valle": 9,
      "Rares Florea": 4,
      "Francis Gil": 9,
      "Joaquín Rodríguez Rodríguez": 4,
      "Juan Luis Garcia Lopez": 6,
      "José Manuel Molina García": 11,
      "Marco Rodríguez Moreno": 8,
      "Antonio Jesús López del Valle": 9,
      "Pedro Exojo Asensio": 7,
      "Pedro Julián Exojo Pérez": 6,
      "Juanma Vázquez (morris)": 10,
      "Carlos Silverio": 6,
      "Gonzalo Gil García": 9,
      "Jose Antonio Aguilera Gómez": 7,
      "Borja Sierra Velázquez": 13,
      "Juan Carlos Molina Camacho": 2,
      "Jorge Luis Rojas Domínguez": 6,
      "Eusebio García Garrocho": 9,
      "Ismael Gómez Cumbreras": 5,
      "Rafa Márquez": 8,
      "Fran Muñoz Muñoz": 8,
      "Jawe Gómez Franco": 4,
      "Arturo Diaz Rosado": 6,
      "Jonathan Domínguez Donoso": 12,
      "Ángel Ponce de Leon Madueño": 5,
      "José Vázquez Garrocho": 5,
      "RoRo Riquelme": 5,
      "Andrea Rodríguez": 6,
      "Alejandra Borrega Martin": 5,
      "Miguel García Garrocho": 5,
      "Manuel Alejandro": 10,
      "Manuel Pérez": 7,
      "Isaías Vázquez Cabeza": 7
    }
  },
  {
    fecha: "2026-06-30",
    equipos: "Dieciseisavos de final (1 punto por partido acertado)",
    resultado: "16 partidos",
    puntos: {
      "José Manuel Cabeza Moreno (Cali)": 7,
      "Miguel Ángel López Martín": 4,
      "Roberto Quintero Sánchez": 4,
      "Sergio Conde Molina": 3,
      "Jaime Borrallo Quiveu": 3,
      "Carlos Molina Prieto": 1,
      "Ángel Manuel Borrega Infante": 5,
      "Stancu Zoran Stefan christian": 3,
      "Rocio Martin Rojas": 3,
      "Antonio Vasluianu": 1,
      "Daniel Garrocho Bogado": 3,
      "Sara Fernández": 2,
      "Rodrigo Exojo Pérez": 4,
      "Silvia Martín Rojas": 3,
      "Ismael Molina Pérez": 3,
      "Oscar De Haro Alcocer": 4,
      "Domingo Rodríguez Gómez": 4,
      "Tomas Doblado Beltrán": 1,
      "Juan Pablo Cerezo Pérez": 6,
      "Jose Angel Maestre Naranjo": 3,
      "Juan Pablo Cerezo Bogado": 4,
      "Rafael Bonilla García": 4,
      "Alvaro Quintero Domiguez": 3,
      "Alejandro Garcia Ponce": 5,
      "Alejandro Quintero Vázquez": 2,
      "Ivan Oliva Rojas": 3,
      "Germán Rojas": 3,
      "Arturo Díaz Prieto": 4,
      "José Manuel Rodríguez Infante": 4,
      "Pedro López": 6,
      "Jesús Ortega": 1,
      "Antonio Blanco Mendez": 1,
      "Francisco José Robles Garrocho": 4,
      "Titola": 2,
      "Manuel Ramon Del Cacho Azcarate": 4,
      "Abraham Márquez Romero": 5,
      "Javier Gavaldá Pérez": 4,
      "Alejandra Domínguez Pozo": 4,
      "Miguel Angel Lopez del valle": 1,
      "Rares Florea": 5,
      "Francis Gil": 5,
      "Joaquín Rodríguez Rodríguez": 0,
      "Juan Luis Garcia Lopez": 2,
      "José Manuel Molina García": 4,
      "Marco Rodríguez Moreno": 3,
      "Antonio Jesús López del Valle": 2,
      "Pedro Exojo Asensio": 4,
      "Pedro Julián Exojo Pérez": 3,
      "Juanma Vázquez (morris)": 5,
      "Carlos Silverio": 2,
      "Gonzalo Gil García": 1,
      "Jose Antonio Aguilera Gómez": 3,
      "Borja Sierra Velázquez": 3,
      "Juan Carlos Molina Camacho": 3,
      "Jorge Luis Rojas Domínguez": 2,
      "Eusebio García Garrocho": 3,
      "Ismael Gómez Cumbreras": 3,
      "Rafa Márquez": 5,
      "Fran Muñoz Muñoz": 1,
      "Jawe Gómez Franco": 4,
      "Arturo Diaz Rosado": 4,
      "Jonathan Domínguez Donoso": 4,
      "Ángel Ponce de Leon Madueño": 2,
      "José Vázquez Garrocho": 2,
      "RoRo Riquelme": 3,
      "Andrea Rodríguez": 3,
      "Alejandra Borrega Martin": 4,
      "Miguel García Garrocho": 1,
      "Manuel Alejandro": 1,
      "Manuel Pérez": 2,
      "Isaías Vázquez Cabeza": 1
    }
  },
  {
    fecha: "2026-07-05",
    equipos: "Octavos de final (2 puntos por partido acertado)",
    resultado: "8 partidos",
    puntos: {
      "José Manuel Cabeza Moreno (Cali)": 0,
      "Miguel Ángel López Martín": 0,
      "Roberto Quintero Sánchez": 0,
      "Sergio Conde Molina": 0,
      "Jaime Borrallo Quiveu": 0,
      "Carlos Molina Prieto": 0,
      "Ángel Manuel Borrega Infante": 0,
      "Stancu Zoran Stefan christian": 2,
      "Rocio Martin Rojas": 0,
      "Antonio Vasluianu": 4,
      "Daniel Garrocho Bogado": 0,
      "Sara Fernández": 0,
      "Rodrigo Exojo Pérez": 0,
      "Silvia Martín Rojas": 0,
      "Ismael Molina Pérez": 6,
      "Oscar De Haro Alcocer": 4,
      "Domingo Rodríguez Gómez": 0,
      "Tomas Doblado Beltrán": 0,
      "Juan Pablo Cerezo Pérez": 0,
      "Jose Angel Maestre Naranjo": 0,
      "Juan Pablo Cerezo Bogado": 0,
      "Rafael Bonilla García": 0,
      "Alvaro Quintero Domiguez": 0,
      "Alejandro Garcia Ponce": 0,
      "Alejandro Quintero Vázquez": 0,
      "Ivan Oliva Rojas": 2,
      "Germán Rojas": 0,
      "Arturo Díaz Prieto": 0,
      "José Manuel Rodríguez Infante": 0,
      "Pedro López": 0,
      "Jesús Ortega": 0,
      "Antonio Blanco Mendez": 2,
      "Francisco José Robles Garrocho": 0,
      "Titola": 0,
      "Manuel Ramon Del Cacho Azcarate": 0,
      "Abraham Márquez Romero": 0,
      "Javier Gavaldá Pérez": 0,
      "Alejandra Domínguez Pozo": 0,
      "Miguel Angel Lopez del valle": 0,
      "Rares Florea": 2,
      "Francis Gil": 2,
      "Joaquín Rodríguez Rodríguez": 2,
      "Juan Luis Garcia Lopez": 0,
      "José Manuel Molina García": 2,
      "Marco Rodríguez Moreno": 0,
      "Antonio Jesús López del Valle": 0,
      "Pedro Exojo Asensio": 0,
      "Pedro Julián Exojo Pérez": 0,
      "Juanma Vázquez (morris)": 0,
      "Carlos Silverio": 0,
      "Gonzalo Gil García": 2,
      "Jose Antonio Aguilera Gómez": 0,
      "Borja Sierra Velázquez": 0,
      "Juan Carlos Molina Camacho": 0,
      "Jorge Luis Rojas Domínguez": 2,
      "Eusebio García Garrocho": 0,
      "Ismael Gómez Cumbreras": 0,
      "Rafa Márquez": 0,
      "Fran Muñoz Muñoz": 0,
      "Jawe Gómez Franco": 0,
      "Arturo Diaz Rosado": 0,
      "Jonathan Domínguez Donoso": 0,
      "Ángel Ponce de Leon Madueño": 0,
      "José Vázquez Garrocho": 0,
      "RoRo Riquelme": 0,
      "Andrea Rodríguez": 0,
      "Alejandra Borrega Martin": 0,
      "Miguel García Garrocho": 0,
      "Manuel Alejandro": 0,
      "Manuel Pérez": 0,
      "Isaías Vázquez Cabeza": 0
    }
  },
  {
    fecha: "2026-07-09",
    equipos: "Cuartos de final (3 puntos por partido acertado)",
    resultado: "Cuartos de final completados: Francia 2-0 Marruecos, España 2-1 Bélgica, Noruega 1-1 Inglaterra y Argentina 1-1 Suiza",
    // Cuartos de final ya completos (los 4 partidos jugados).
    // Cuando empiecen las semifinales, añade un nuevo bloque al final de este array.
    puntos: {
      "José Manuel Cabeza Moreno (Cali)": 3,
      "Miguel Ángel López Martín": 6,
      "Roberto Quintero Sánchez": 3,
      "Sergio Conde Molina": 0,
      "Jaime Borrallo Quiveu": 3,
      "Carlos Molina Prieto": 0,
      "Ángel Manuel Borrega Infante": 0,
      "Stancu Zoran Stefan christian": 6,
      "Rocio Martin Rojas": 0,
      "Antonio Vasluianu": 0,
      "Daniel Garrocho Bogado": 0,
      "Sara Fernández": 6,
      "Rodrigo Exojo Pérez": 0,
      "Silvia Martín Rojas": 6,
      "Ismael Molina Pérez": 0,
      "Oscar De Haro Alcocer": 0,
      "Domingo Rodríguez Gómez": 3,
      "Tomas Doblado Beltrán": 3,
      "Juan Pablo Cerezo Pérez": 3,
      "Jose Angel Maestre Naranjo": 3,
      "Juan Pablo Cerezo Bogado": 3,
      "Rafael Bonilla García": 0,
      "Alvaro Quintero Domiguez": 3,
      "Alejandro Garcia Ponce": 6,
      "Alejandro Quintero Vázquez": 0,
      "Ivan Oliva Rojas": 6,
      "Germán Rojas": 9,
      "Arturo Díaz Prieto": 6,
      "José Manuel Rodríguez Infante": 3,
      "Pedro López": 3,
      "Jesús Ortega": 0,
      "Antonio Blanco Mendez": 0,
      "Francisco José Robles Garrocho": 6,
      "Titola": 0,
      "Manuel Ramon Del Cacho Azcarate": 0,
      "Abraham Márquez Romero": 0,
      "Javier Gavaldá Pérez": 3,
      "Alejandra Domínguez Pozo": 6,
      "Miguel Angel Lopez del valle": 6,
      "Rares Florea": 3,
      "Francis Gil": 0,
      "Joaquín Rodríguez Rodríguez": 6,
      "Juan Luis Garcia Lopez": 0,
      "José Manuel Molina García": 0,
      "Marco Rodríguez Moreno": 3,
      "Antonio Jesús López del Valle": 3,
      "Pedro Exojo Asensio": 0,
      "Pedro Julián Exojo Pérez": 0,
      "Juanma Vázquez (morris)": 0,
      "Carlos Silverio": 3,
      "Gonzalo Gil García": 3,
      "Jose Antonio Aguilera Gómez": 3,
      "Borja Sierra Velázquez": 0,
      "Juan Carlos Molina Camacho": 3,
      "Jorge Luis Rojas Domínguez": 0,
      "Eusebio García Garrocho": 3,
      "Ismael Gómez Cumbreras": 3,
      "Rafa Márquez": 0,
      "Fran Muñoz Muñoz": 0,
      "Jawe Gómez Franco": 0,
      "Arturo Diaz Rosado": 0,
      "Jonathan Domínguez Donoso": 3,
      "Ángel Ponce de Leon Madueño": 0,
      "José Vázquez Garrocho": 3,
      "RoRo Riquelme": 3,
      "Andrea Rodríguez": 0,
      "Alejandra Borrega Martin": 9,
      "Miguel García Garrocho": 0,
      "Manuel Alejandro": 0,
      "Manuel Pérez": 6,
      "Isaías Vázquez Cabeza": 0
    }
  }
];

// 3) Próximos partidos (para el recuadro "Próximos partidos" de la web).
//    "puntosRonda" es el número de puntos que vale acertar un partido de esta ronda (se muestra
//    junto al título del recuadro). Edita la lista de partidos según se vayan jugando:
//    quita los que ya se jugaron y añade los siguientes (semifinales, final, etc.), actualizando
//    "puntosRonda" si cambia el valor de los puntos.
const puntosRonda = 3;
const proximosPartidos = [];

// 4) Ranking justo antes de esta última actualización (para poder mostrar flechas de
//    subida/bajada en la clasificación). Cada vez que actualices los puntos:
//    1) antes de tocar nada, copia el orden ACTUAL de la clasificación aquí abajo
//    2) luego actualiza los puntos de partidos arriba
//    Así la web puede comparar el antes y el después.
const rankingAnterior = [
  "Pedro López",
  "José Manuel Rodríguez Infante",
  "Jonathan Domínguez Donoso",
  "José Manuel Cabeza Moreno (Cali)",
  "Juan Pablo Cerezo Pérez",
  "Silvia Martín Rojas",
  "Oscar De Haro Alcocer",
  "Alejandro Garcia Ponce",
  "Germán Rojas",
  "Javier Gavaldá Pérez",
  "José Manuel Molina García",
  "Miguel Ángel López Martín",
  "Alejandra Domínguez Pozo",
  "Francis Gil",
  "Borja Sierra Velázquez",
  "Stancu Zoran Stefan christian",
  "Sara Fernández",
  "Ismael Molina Pérez",
  "Ivan Oliva Rojas",
  "Antonio Blanco Mendez",
  "Juanma Vázquez (morris)",
  "Gonzalo Gil García",
  "Alejandra Borrega Martin",
  "Abraham Márquez Romero",
  "Rares Florea",
  "Antonio Jesús López del Valle",
  "Roberto Quintero Sánchez",
  "Jose Angel Maestre Naranjo",
  "Francisco José Robles Garrocho",
  "Miguel Angel Lopez del valle",
  "Rafa Márquez",
  "Ángel Manuel Borrega Infante",
  "Rodrigo Exojo Pérez",
  "Domingo Rodríguez Gómez",
  "Alvaro Quintero Domiguez",
  "Manuel Ramon Del Cacho Azcarate",
  "Eusebio García Garrocho",
  "Manuel Pérez",
  "Daniel Garrocho Bogado",
  "Arturo Díaz Prieto",
  "Marco Rodríguez Moreno",
  "Pedro Exojo Asensio",
  "Carlos Silverio",
  "Ismael Gómez Cumbreras",
  "RoRo Riquelme",
  "Manuel Alejandro",
  "Sergio Conde Molina",
  "Rocio Martin Rojas",
  "Antonio Vasluianu",
  "Tomas Doblado Beltrán",
  "Jose Antonio Aguilera Gómez",
  "Jorge Luis Rojas Domínguez",
  "Arturo Diaz Rosado",
  "José Vázquez Garrocho",
  "Jaime Borrallo Quiveu",
  "Juan Pablo Cerezo Bogado",
  "Titola",
  "Joaquín Rodríguez Rodríguez",
  "Pedro Julián Exojo Pérez",
  "Fran Muñoz Muñoz",
  "Andrea Rodríguez",
  "Carlos Molina Prieto",
  "Juan Luis Garcia Lopez",
  "Juan Carlos Molina Camacho",
  "Jawe Gómez Franco",
  "Isaías Vázquez Cabeza",
  "Jesús Ortega",
  "Ángel Ponce de Leon Madueño",
  "Rafael Bonilla García",
  "Alejandro Quintero Vázquez",
  "Miguel García Garrocho"
];
